# .github/workflows/release.yml
name: changelog

on:
  workflow_dispatch:
    inputs:
      from_tag:
        description: "Starting Tag"
        required: true
        type: string
      to_tag:
        description: "Release version"
        required: true
        type: string

permissions:
  contents: write
  # packages: write
  # issues: write
  # id-token: write

jobs:
  changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Build Changelog
        id: github_release_changelog
        uses: mikepenz/release-changelog-builder-action@v5
        with:
          fromTag: ${{ from_tag }}
          toTag: ${{ to_tag }}
          configurationJson: |
            {
                "categories": [
                    {
                      "title": "## 🚀 Features",
                      "labels": ["feature","feat","Feature","Feat"]
                    },
                    {
                      "title": "## 🐛 Fixes",
                      "labels": ["fix","fixes", "bug", "bugs", "Fix", "Fixes", "Bug", "Bugs"]
                    },
                    {
                      "title": "## 🧪 Tests",
                      "labels": ["test", "tests", "Test", "Tests"]
                    },
                    {
                      "title": "## 📦 Uncategorized",
                      "labels": []
                    }
                  ],
                "label_extractor": [
                    {
                        "pattern": "^.?(build|chore|ci|docs|feat|fix|perf|refactor|revert|style|test|tests).?.*",
                        "target": "$1",
                        "method": "regexr",
                        "on_property": "title"
                    }
                ],
                "sort": "ASC",
                "template": "${{CHANGELOG}}",
                "pr_template": "- ${{TITLE}}\n   - PR: #${{NUMBER}}",
                "empty_template": "- no changes",
                "max_pull_requests": 1000,
                "max_back_track_time_days": 1000
            }
      - name: Update Release
        uses: mikepenz/action-gh-release@v0.2.0-a03 #softprops/action-gh-release
        with:
          tag_name: ${{ to_tag }}
          body: ${{steps.github_release_changelog.outputs.changelog}}
